# Generated by Django 4.0.3 on 2022-04-26 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_shoppinglist_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('--', '--'), ('Male', 'Male'), ('Female', 'Female')], default='--', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=1234567890, max_digits=10),
            preserve_default=False,
        ),
    ]
