# Generated by Django 4.0.3 on 2022-04-13 11:27

import Recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(upload_to=Recipe.models.upload_path_handler),
        ),
    ]
