# Generated by Django 4.0.3 on 2022-04-14 03:55

import Recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(upload_to=Recipe.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='missingIngredients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
