# Generated by Django 4.0.3 on 2022-04-28 17:25

import Recipe.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0008_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(upload_to=Recipe.models.upload_path_handler),
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_cuisine', to='Recipe.recipe')),
            ],
        ),
    ]
