# Generated by Django 4.0.3 on 2022-05-15 19:41

import Recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0012_remove_cuisine_recipe_recipe_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='cuisine_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Recipe.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(upload_to=Recipe.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Recipe.models.upload_path_handler),
        ),
    ]
